# Generated by Django 4.1.5 on 2023-04-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=20)),
                ('itemlabel', models.CharField(max_length=100, null=True)),
                ('itemdesc', models.CharField(max_length=500, null=True)),
                ('subject_id', models.CharField(max_length=20, null=True)),
                ('subjectlabel', models.CharField(max_length=100, null=True)),
                ('donatedby_id', models.CharField(max_length=20, null=True)),
                ('donatedbylabel', models.CharField(max_length=100, null=True)),
                ('colltypelabel', models.CharField(max_length=30, null=True)),
                ('inventorynum', models.CharField(max_length=30, null=True)),
                ('describedat', models.URLField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Corp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=20)),
                ('itemlabel', models.CharField(max_length=50)),
                ('itemdesc', models.CharField(max_length=100, null=True)),
                ('streetaddress', models.CharField(max_length=255, null=True)),
                ('instanceoflabel', models.CharField(max_length=50, null=True)),
                ('inception', models.DateField(null=True)),
                ('dissolved', models.DateField(null=True)),
                ('dateofopening', models.DateField(null=True)),
                ('dateofclosure', models.DateField(null=True)),
                ('website', models.URLField(max_length=255, null=True)),
                ('location', models.CharField(max_length=20, null=True)),
                ('locationlabel', models.CharField(max_length=50, null=True)),
                ('coordinates', models.CharField(max_length=200, null=True)),
                ('subject_id', models.CharField(max_length=20, null=True)),
                ('subjectlabel', models.CharField(max_length=50, null=True)),
                ('parentorg_id', models.CharField(max_length=20, null=True)),
                ('parentorglabel', models.CharField(max_length=50, null=True)),
                ('owner_id', models.CharField(max_length=20, null=True)),
                ('ownerlabel', models.CharField(max_length=50, null=True)),
                ('ownerdesc', models.CharField(max_length=200, null=True)),
                ('collection_id', models.CharField(max_length=20, null=True)),
                ('inventorynum', models.CharField(max_length=20, null=True)),
                ('describedat', models.URLField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('primarykey', models.BigAutoField(primary_key=True, serialize=False)),
                ('errclasstype', models.CharField(max_length=50)),
                ('errvalue', models.CharField(max_length=20)),
                ('stacktrace', models.TextField()),
                ('procedure', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('qcode', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OralHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=20)),
                ('oralhistorylabel', models.CharField(max_length=100, null=True)),
                ('inventorynum', models.CharField(max_length=20, null=True)),
                ('describedat', models.URLField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=20)),
                ('image', models.URLField(null=True)),
                ('itemlabel', models.CharField(max_length=50)),
                ('itemdesc', models.CharField(max_length=100, null=True)),
                ('dob', models.CharField(max_length=30, null=True)),
                ('placeofbirth_id', models.CharField(max_length=20, null=True)),
                ('placeofbirthlabel', models.CharField(max_length=50, null=True)),
                ('dateofdeath', models.CharField(max_length=30, null=True)),
                ('placeofdeath_id', models.CharField(max_length=20, null=True)),
                ('placeofdeathlabel', models.CharField(max_length=50, null=True)),
                ('occupation_id', models.CharField(max_length=20, null=True)),
                ('occupationlabel', models.CharField(max_length=50, null=True)),
                ('fieldofwork_id', models.CharField(max_length=20, null=True)),
                ('fieldofworklabel', models.CharField(max_length=50, null=True)),
                ('motherlabel', models.CharField(max_length=50, null=True)),
                ('fatherlabel', models.CharField(max_length=50, null=True)),
                ('siblinglabel', models.CharField(max_length=50, null=True)),
                ('spouselabel', models.CharField(max_length=50, null=True)),
                ('childlabel', models.CharField(max_length=50, null=True)),
                ('relativelabel', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subjectlabel', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WdQuery',
            fields=[
                ('querytitle', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('querytext', models.TextField()),
            ],
        ),
    ]
