# Generated by Django 4.1.5 on 2023-03-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('item_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('image', models.URLField()),
                ('itemlabel', models.CharField(max_length=50)),
                ('itemdesc', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('placeofbirth_id', models.CharField(max_length=20)),
                ('placeofbirthlabel', models.CharField(max_length=50)),
                ('dateofdeath', models.DateField()),
                ('placeofdeath_id', models.CharField(max_length=20)),
                ('placeofdeathlabel', models.CharField(max_length=50)),
                ('occupation_id', models.CharField(max_length=20)),
                ('occupationlabel', models.CharField(max_length=50)),
                ('fieldofwork_id', models.CharField(max_length=20)),
                ('fieldofworklabel', models.CharField(max_length=50)),
                ('motherlabel', models.CharField(max_length=50)),
                ('fatherlabel', models.CharField(max_length=50)),
                ('siblinglabel', models.CharField(max_length=50)),
                ('spouselabel', models.CharField(max_length=50)),
                ('childlabel', models.CharField(max_length=50)),
                ('relativelabel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WdQuery',
            fields=[
                ('querytitle', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('querytext', models.TextField()),
            ],
        ),
    ]
