# Generated by Django 4.1.5 on 2023-04-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oralhistory',
            name='itemlabel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
