# Generated by Django 4.1.5 on 2023-04-18 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0002_oralhistory_itemlabel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oralhistory',
            old_name='oralhistorylabel',
            new_name='itemdesc',
        ),
    ]
