# Generated by Django 4.1.5 on 2023-04-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0003_rename_oralhistorylabel_oralhistory_itemdesc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Corp',
            new_name='CorpBody',
        ),
    ]
