# Generated by Django 4.1.5 on 2023-04-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0004_rename_corp_corpbody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpbody',
            name='itemdesc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='corpbody',
            name='itemlabel',
            field=models.CharField(max_length=100),
        ),
    ]
