# Generated by Django 4.1.5 on 2023-04-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0005_alter_corpbody_itemdesc_alter_corpbody_itemlabel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpbody',
            name='collection_id',
        ),
        migrations.AddField(
            model_name='corpbody',
            name='collection',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='corpbody',
            name='parentorglabel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
