# Generated by Django 4.1.5 on 2023-04-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0005_alter_collection_describedat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=20)),
                ('itemlabel', models.CharField(max_length=50)),
                ('itemdesc', models.CharField(max_length=100, null=True)),
                ('streetaddress', models.CharField(max_length=255, null=True)),
                ('instanceoflabel', models.CharField(max_length=50, null=True)),
                ('inception', models.DateField(null=True)),
                ('dissolved', models.DateField(null=True)),
                ('dateofopening', models.DateField(null=True)),
                ('dateofclosure', models.DateField(null=True)),
                ('website', models.URLField(max_length=255, null=True)),
                ('location', models.CharField(max_length=20, null=True)),
                ('locationlabel', models.CharField(max_length=50, null=True)),
                ('coordinates', models.CharField(max_length=200, null=True)),
                ('subject_id', models.CharField(max_length=20, null=True)),
                ('subjectlabel', models.CharField(max_length=50, null=True)),
                ('parentorg_id', models.CharField(max_length=20, null=True)),
                ('parentorglabel', models.CharField(max_length=50, null=True)),
                ('owner_id', models.CharField(max_length=20, null=True)),
                ('ownerlabel', models.CharField(max_length=50, null=True)),
                ('ownerdesc', models.CharField(max_length=200, null=True)),
                ('collection_id', models.CharField(max_length=20, null=True)),
                ('inventorynum', models.CharField(max_length=20, null=True)),
                ('describedat', models.URLField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OralHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=20)),
                ('oralhistorylabel', models.CharField(max_length=100, null=True)),
                ('inventorynum', models.CharField(max_length=20, null=True)),
                ('describedat', models.URLField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('item_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('itemlabel', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
