# Generated by Django 4.1.8 on 2023-04-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0007_corpbody_instanceof_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorLog',
        ),
        migrations.AddField(
            model_name='oralhistory',
            name='subject_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='oralhistory',
            name='subjectlabel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
