# Generated by Django 4.1.8 on 2023-04-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0008_delete_errorlog_oralhistory_subject_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oralhistory',
            name='itemdesc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
