# Generated by Django 4.1.8 on 2023-04-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0011_relationtype_relation_type_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtype',
            name='list_order',
            field=models.IntegerField(null=True),
        ),
    ]
