# Generated by Django 4.1.9 on 2023-06-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0012_relationtype_list_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpbody',
            name='dateofclosure',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='corpbody',
            name='dateofopening',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='corpbody',
            name='dissolved',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='corpbody',
            name='inception',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
