# Generated by Django 4.1.9 on 2023-10-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0013_alter_corpbody_dateofclosure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationtype',
            old_name='domain',
            new_name='app_class',
        ),
    ]
