# Generated by Django 4.1.5 on 2023-03-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=20)),
                ('itemlabel', models.CharField(max_length=30, null=True)),
                ('itemdesc', models.CharField(max_length=100, null=True)),
                ('colltypelabel', models.CharField(max_length=20, null=True)),
                ('inventorynum', models.CharField(max_length=20, null=True)),
                ('describedat', models.URLField(null=True)),
            ],
        ),
    ]
