# Generated by Django 4.1.5 on 2023-03-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0002_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='colltypelabel',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='itemlabel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
