# Generated by Django 4.1.5 on 2023-03-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0003_alter_collection_colltypelabel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='inventorynum',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='itemdesc',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
