# Generated by Django 4.1.5 on 2023-03-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0004_alter_collection_inventorynum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='describedat',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
